import fs from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { TextDecoder } from "node:util";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DATA_PATH = path.join(ROOT, "data", "site-data.json");
const THS_JS_PATH = path.join(ROOT, "scripts", "ths.js");
const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36";
const DATASET = {
  industry: { label: "行业", referer: "http://data.10jqka.com.cn/funds/hyzjl/", path: "hyzjl", field: "je", parser: parseBoardRow },
  concept: { label: "概念", referer: "http://data.10jqka.com.cn/funds/gnzjl/", path: "gnzjl", field: "je", parser: parseBoardRow },
  stock: { label: "个股", referer: "http://data.10jqka.com.cn/funds/ggzjl/", path: "ggzjl", field: "zdf", parser: parseStockRow }
};

function hkNow() { return new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Hong_Kong" })); }
function fmtDate(date) { return date.getFullYear() + "-" + String(date.getMonth() + 1).padStart(2, "0") + "-" + String(date.getDate()).padStart(2, "0"); }
function fmtDateTime(date) { return fmtDate(date) + " " + String(date.getHours()).padStart(2, "0") + ":" + String(date.getMinutes()).padStart(2, "0"); }
function stripTags(html) { return html.replace(/<!--[\s\S]*?-->/g, "").replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/\s+/g, " ").trim(); }
function tableRows(html) { const clean = html.replace(/<!--[\s\S]*?-->/g, ""); const rows = []; for (const rowMatch of clean.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)) { const cells = Array.from(rowMatch[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)).map(function(cell) { return stripTags(cell[1]); }); if (cells.length) rows.push(cells); } return rows; }
function parseNumber(text) { if (text === null || text === undefined) return 0; const cleaned = String(text).replace(/,/g, "").replace(/%/g, "").replace(/\+/g, "").trim(); if (!cleaned || cleaned === "-" || cleaned === "--") return 0; const match = cleaned.match(/-?\d+(?:\.\d+)?/); return match ? Number(match[0]) : 0; }
function moneyToYuan(text, defaultUnit) { const raw = String(text || "").trim(); const number = parseNumber(raw); if (raw.includes("亿") || defaultUnit === "亿") return number * 100000000; if (raw.includes("万") || defaultUnit === "万") return number * 10000; return number; }
function statusFor(netFlow, changePct) { if (netFlow > 0 && changePct >= 0) return "增强"; if (netFlow < 0 && changePct <= 0) return "转弱"; if (netFlow > 0 && changePct < 0) return "分歧"; if (netFlow < 0 && changePct > 0) return "背离"; return "中性"; }
function parseBoardRow(cells, kind) { if (cells.length < 7) return null; const inflow = moneyToYuan(cells[4], "亿"); const outflow = moneyToYuan(cells[5], "亿"); const netFlow = moneyToYuan(cells[6], "亿"); const changePct = parseNumber(cells[3]); return { name: cells[1], category: kind, indexValue: parseNumber(cells[2]), changePct: changePct, inflow: inflow, outflow: outflow, netFlow: netFlow, flowRate: inflow + outflow ? Number((netFlow / (inflow + outflow) * 100).toFixed(2)) : 0, memberCount: parseNumber(cells[7]), leader: cells[8] ? (cells[8] + " " + (cells[9] || "")).trim() : "--", note: cells[8] ? (cells[8] + " " + (cells[9] || "")).trim() : "--", status: statusFor(netFlow, changePct) }; }
function parseStockRow(cells) { if (cells.length < 10) return null; const inflow = moneyToYuan(cells[6]); const outflow = moneyToYuan(cells[7]); const netFlow = moneyToYuan(cells[8]); const amount = moneyToYuan(cells[9]); const changePct = parseNumber(cells[4]); return { code: cells[1], name: cells[2], category: "个股", price: parseNumber(cells[3]), changePct: changePct, turnoverRate: cells[5], inflow: inflow, outflow: outflow, netFlow: netFlow, amount: amount, flowRate: amount ? Number((netFlow / amount * 100).toFixed(2)) : 0, note: "换手 " + cells[5], status: statusFor(netFlow, changePct) }; }
async function makeTokenFactory() { const js = await fs.readFile(THS_JS_PATH, "utf8"); const context = { window: {}, document: {}, navigator: { userAgent: USER_AGENT }, location: {}, console: console }; vm.createContext(context); vm.runInContext(js, context); return function() { return vm.runInContext("v()", context); }; }
async function fetchPage(dataset, page, tokenFactory) { const pagePart = page ? "page/" + page + "/" : ""; const url = "http://data.10jqka.com.cn/funds/" + dataset.path + "/field/" + dataset.field + "/order/desc/" + pagePart + "ajax/1/free/1/"; const token = tokenFactory(); const res = await fetch(url, { headers: { "User-Agent": USER_AGENT, "X-Requested-With": "XMLHttpRequest", "hexin-v": token, Referer: dataset.referer, Accept: "text/html, */*; q=0.01", "Cache-Control": "no-cache", Pragma: "no-cache" } }); if (!res.ok) throw new Error(dataset.label + "资金流获取失败：HTTP " + res.status + " page=" + (page || 1)); const buffer = Buffer.from(await res.arrayBuffer()); return new TextDecoder("gb18030").decode(buffer); }
async function fetchDataset(key, tokenFactory) { const dataset = DATASET[key]; const first = await fetchPage(dataset, null, tokenFactory); const pageInfo = first.match(/page_info[^>]*>([^<]+)/); const totalPages = pageInfo ? Number(String(pageInfo[1]).split("/")[1]) : 1; const htmlList = [first]; for (let page = 2; page <= totalPages; page += 1) { htmlList.push(await fetchPage(dataset, page, tokenFactory)); if (key === "stock" && page % 20 === 0) await new Promise(function(resolve) { setTimeout(resolve, 250); }); } const rows = htmlList.flatMap(function(html) { return tableRows(html); }); const parsed = rows.map(function(cells) { return dataset.parser(cells, dataset.label); }).filter(Boolean); return parsed.sort(function(a, b) { return Number(b.netFlow || 0) - Number(a.netFlow || 0); }); }
function moneyText(value) { const n = Number(value || 0); if (Math.abs(n) >= 100000000) return (n / 100000000).toFixed(1) + "亿"; if (Math.abs(n) >= 10000) return (n / 10000).toFixed(1) + "万"; return n.toFixed(0); }
function pctText(value) { return Number(value || 0).toFixed(2) + "%"; }
function names(rows) { return rows.map(function(row) { return row.name; }).filter(Boolean).join("、") || "暂无数据"; }
function buildSignals(industries, concepts, stocks) { const signals = []; const topIndustry = industries[0]; const topConcept = concepts[0]; const topStock = stocks[0]; const weakIndustry = industries.slice().sort(function(a,b){ return a.netFlow - b.netFlow; })[0]; const weakStock = stocks.slice().sort(function(a,b){ return a.netFlow - b.netFlow; })[0]; if (topIndustry) signals.push({ name: topIndustry.name, type: "行业", description: "行业净流入 " + moneyText(topIndustry.netFlow) + "，涨跌幅 " + pctText(topIndustry.changePct) + "。" }); if (topConcept) signals.push({ name: topConcept.name, type: "概念", description: "概念净流入 " + moneyText(topConcept.netFlow) + "，覆盖成分 " + (topConcept.memberCount || "--") + " 只。" }); if (topStock) signals.push({ name: topStock.name, type: "个股", description: "个股净流入 " + moneyText(topStock.netFlow) + "，涨跌幅 " + pctText(topStock.changePct) + "。" }); if (weakIndustry) signals.push({ name: weakIndustry.name, type: "流出", description: "行业净流出 " + moneyText(Math.abs(weakIndustry.netFlow)) + "，资金承压。" }); if (weakStock) signals.push({ name: weakStock.name, type: "流出", description: "个股净流出 " + moneyText(Math.abs(weakStock.netFlow)) + "，需观察是否拖累相关方向。" }); return signals; }
function buildReport(industries, concepts, stocks) { const topIndustries = industries.slice(0, 3); const weakIndustries = industries.slice().sort(function(a,b){ return a.netFlow - b.netFlow; }).slice(0, 3); const topConcepts = concepts.slice(0, 3); const topStocks = stocks.slice(0, 5); return { title: "今日复盘：同花顺资金流观察", paragraphs: ["行业资金流入靠前的是 " + names(topIndustries) + "；资金流出压力较大的方向是 " + names(weakIndustries) + "。", "概念层面，" + names(topConcepts) + " 的净流入居前，说明短线资金更集中在这些主题方向。", "个股净流入靠前的是 " + names(topStocks) + "。如果这些个股同时属于同一行业或概念，后续可以作为主线延续性的观察点。"], bullets: ["解释规则：净流入与上涨同步视为增强，净流入但下跌视为分歧，净流出且下跌视为转弱。", "当前口径：同花顺行业、概念、个股资金流；不再标注为申万行业口径。", "数据来自公开页面，若某天接口波动，页面会保留最近一次可用数据并提示。"] }; }
async function main() { await fs.mkdir(path.dirname(DATA_PATH), { recursive: true }); const tokenFactory = await makeTokenFactory(); const industries = await fetchDataset("industry", tokenFactory); const concepts = await fetchDataset("concept", tokenFactory); const stocks = await fetchDataset("stock", tokenFactory); const now = hkNow(); const payload = { meta: { tradingDay: fmtDate(now), generatedAt: fmtDateTime(now), taxonomy: "同花顺行业 / 概念 / 个股资金流", dataMode: "live", dataWarning: "真实数据来自同花顺公开资金流页面；行业与概念分类为同花顺口径，不是申万分类。", coverageNote: "第一版展示当日资金流快照；历史序列将在每日自动更新后逐步沉淀。", fundFlowCoverage: { targetStart: "上线日起每日沉淀", actualStart: fmtDate(now), statusText: "同花顺实时资金流" }, counts: { industries: industries.length, concepts: concepts.length, stocks: stocks.length } }, industries: industries, concepts: concepts, stocks: stocks, signals: buildSignals(industries, concepts, stocks), report: buildReport(industries, concepts, stocks) }; await fs.writeFile(DATA_PATH, JSON.stringify(payload, null, 2), "utf8"); console.log("wrote " + DATA_PATH); console.log("industry=" + industries.length + " concept=" + concepts.length + " stock=" + stocks.length); }
await main().catch(async function(error) { try { const previous = JSON.parse(await fs.readFile(DATA_PATH, "utf8")); previous.meta = previous.meta || {}; previous.meta.dataWarning = "本次同花顺真实数据更新失败，继续展示最近一次数据。原因：" + error.message; previous.meta.generatedAt = fmtDateTime(hkNow()); previous.meta.fundFlowCoverage = previous.meta.fundFlowCoverage || {}; previous.meta.fundFlowCoverage.statusText = "更新失败，沿用快照"; await fs.writeFile(DATA_PATH, JSON.stringify(previous, null, 2), "utf8"); } catch (_) {} console.error(error); });
