const M=MarketCore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=2)=>M.valid(v)?Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d,maximumFractionDigits:d}):'--';
const money=v=>!M.valid(v)?'--':Math.abs(v)>=1e8?num(v/1e8)+'亿':num(v/1e4)+'万';
const pct=v=>M.valid(v)?(v>0?'+':'')+num(v)+'%':'--';
const tone=v=>v>0?'up':v<0?'down':'muted';
const idOf=r=>r.category+':'+(r.code||r.name);
const exchange=c=>/^6/.test(c)?'sh':/^[03]/.test(c)?'sz':/^[489]/.test(c)?'bj':'';
const ico=name=>`<i data-lucide="${name}"></i>`;
const iconButton=(name,title,attrs='')=>`<button class="icon-button" title="${title}" aria-label="${title}" ${attrs}>${ico(name)}</button>`;
const empty=text=>`<div class="empty">${esc(text)}</div>`;
const loading=()=>'<div class="loading-surface"><span></span>正在读取数据</div>';
const routes={overview:['市场总览','MARKET OVERVIEW'],rotation:['板块轮动','SECTOR ROTATION'],industry:['行业资金','INDUSTRY FLOW'],concept:['概念热点','THEMATIC FLOW'],stock:['个股探索','STOCK EXPLORER'],watch:['我的自选','PERSONAL WATCHLIST'],events:['快讯与公告','MARKET INTELLIGENCE'],report:['每日复盘','DAILY RESEARCH'],sources:['数据中心','DATA COVERAGE']};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
const storedWatch=stored('a-watch',[]);
const S={data:null,market:{indices:[]},quotes:{records:{}},history:{records:{}},analytics:{calendar:[],availableDates:[],boardSeries:{},boardStats:{},stockStats:{}},events:{news:[],announcements:[]},archive:[],date:'latest',view:'overview',index:'sh000001',range:120,priceMode:'candle',treeMetric:'netFlow',rotationType:'行业',rotationDays:10,chartMode:'table',query:'',direction:'all',exchange:'all',preset:'all',noST:false,peMax:'',capMin:'',turnMin:'',flowMin:'',sort:'netFlow',sortDirection:-1,page:1,watch:new Set(Array.isArray(storedWatch)?storedWatch:[]),notes:stored('a-notes',{}),compare:[],charts:[],detailCharts:[],detail:null,detailTab:'price',detailRange:120,eventType:'all',eventCategory:'all',eventQuery:'',eventPage:1,request:0,detailRequest:0,kline:new Map(),stockFlows:null};
if(stored('a-theme','light')==='dark')document.body.classList.add('dark');
function icons(){window.lucide?.createIcons({attrs:{width:17,height:17,'stroke-width':1.7}});}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(S.toastTimer);S.toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{toast('当前浏览器无法保存，本次修改只在当前页面有效');return false;}}
async function getJSON(url){const r=await fetch(url,{cache:'no-cache',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
async function load(){const ticket=++S.request;$('#refresh').disabled=true;try{
 const d=await getJSON(S.date==='latest'?'data/site-data.json':`data/history/${S.date}.json`);
 const paths=['market-data','quotes','index-history','analytics','events','history/index','research-status'];
 const results=await Promise.allSettled(paths.map(p=>getJSON('data/'+p+'.json')));if(ticket!==S.request)return;S.data=d;
 const keys=['market','quotes','history','analytics','events','archive','researchStatus'];results.forEach((r,i)=>{if(r.status==='fulfilled')S[keys[i]]=i===5?r.value.entries:r.value;});
 $('#date-select').innerHTML='<option value="latest">最新收盘快照</option>'+S.archive.slice().reverse().map(e=>`<option value="${e.date}">${e.date}</option>`).join('');$('#date-select').value=S.date;
 render();
 }catch(e){$('#alert').hidden=false;$('#alert').textContent='读取失败，'+e.message+'。请重新读取。';if(!S.data)$('#content').innerHTML=empty('暂时无法读取数据');}finally{if(ticket===S.request)$('#refresh').disabled=false;}}
const day=()=>S.data?.meta?.tradingDay||'';
const allBase=()=>[...(S.data?.industries||[]),...(S.data?.concepts||[]),...(S.data?.stocks||[])];
function seriesFor(r){if(r.code){return S.stockFlows?S.stockFlows.dates.map((d,i)=>[d,S.stockFlows.records[r.code]?.[i]??null]):[];}return(S.analytics.boardSeries[idOf(r)]||[]).map(x=>[x[0],x[1]]);}
function enrich(r){const q=S.quotes.records?.[r.code];let stats;
 if(S.analytics.asOf===day())stats=r.code?S.analytics.stockStats[r.code]:S.analytics.boardStats[idOf(r)];
 else if(!r.code||S.stockFlows)stats=M.stockStats(S.analytics.calendar,seriesFor(r),day());
 return {...r,price:r.price??r.indexValue,exchange:exchange(r.code),...(q&&q.date===day()?{price:q.price,pe:q.pe,pb:q.pb,marketCap:q.marketCap,floatCap:q.floatCap,turnover:q.turnover,high:q.high,low:q.low,open:q.open,previous:q.previous,limitUp:q.limitUp,limitDown:q.limitDown,quoteDate:q.date}:{}),stats:stats||{flow5:{value:null,covered:0,total:5},flow20:{value:null,covered:0,total:20},streak:null,delta:null}};}
function baseRows(){return S.view==='watch'?allBase().filter(r=>S.watch.has(idOf(r))):S.data?.[{stock:'stocks',concept:'concepts',industry:'industries'}[S.view]]||[];}
function tableRows(){return M.sortRows(M.filterRows(baseRows().map(enrich),S),S.sort,S.sortDirection);}
function dispose(detail=false){const list=detail?S.detailCharts:S.charts;list.forEach(c=>c.dispose());list.length=0;}
function colors(){const css=getComputedStyle(document.body);return Object.fromEntries(['ink','muted','line','red','green','accent','surface'].map(k=>[k,css.getPropertyValue('--'+k).trim()]));}
function chart(id,option,detail=false){const node=typeof id==='string'?$(id):id;if(!node)return null;if(!window.echarts){node.innerHTML=empty('图表组件读取失败');return null;}const c=colors(),instance=echarts.init(node,null,{renderer:'canvas'});instance.setOption({animation:false,textStyle:{fontFamily:'Microsoft YaHei, Arial',color:c.muted,fontSize:11},backgroundColor:'transparent',...option});(detail?S.detailCharts:S.charts).push(instance);return instance;}
function lineChart(node,dates,series,detail=false){const c=colors();return chart(node,{tooltip:{trigger:'axis',confine:true,valueFormatter:v=>num(v)+'亿'},legend:{top:3,textStyle:{color:c.muted,fontSize:11}},grid:{left:55,right:20,top:36,bottom:50},xAxis:{type:'category',data:dates,axisLabel:{formatter:v=>v.slice(5)},axisLine:{lineStyle:{color:c.line}}},yAxis:{type:'value',name:'亿元',splitLine:{lineStyle:{color:c.line}}},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:8,borderColor:c.line}],series:series.map((s,i)=>({name:s.name,type:'line',showSymbol:false,connectNulls:false,lineStyle:{width:2},itemStyle:{color:[c.accent,'#bd8c35','#8a75aa',c.red][i%4]},...s}))},detail);}
function candles(node,rows,{detail=false,mode='candle',range=120}={}){
 if(!rows.length){$(node).innerHTML=empty('此日期范围没有可用日线');return;}const c=colors(),dates=rows.map(r=>r[0]);
 const option={tooltip:{trigger:'axis',axisPointer:{type:'cross'},confine:true},axisPointer:{link:[{xAxisIndex:'all'}]},legend:{data:['日K','收盘','MA5','MA20'],top:0,textStyle:{color:c.muted,fontSize:10}},grid:[{left:58,right:25,top:32,height:'57%'},{left:58,right:25,top:'75%',height:'12%'}],xAxis:[{type:'category',data:dates,boundaryGap:true,axisLabel:{show:false},axisLine:{lineStyle:{color:c.line}}},{type:'category',gridIndex:1,data:dates,axisLabel:{formatter:v=>v.slice(5)},axisLine:{lineStyle:{color:c.line}}}],yAxis:[{scale:true,splitLine:{lineStyle:{color:c.line}},axisLabel:{formatter:v=>num(v,0)}},{scale:true,gridIndex:1,splitNumber:1,splitLine:{show:false},axisLabel:{show:false},name:'成交量',nameTextStyle:{fontSize:10}}],dataZoom:[{type:'inside',xAxisIndex:[0,1],start:Math.max(0,100-range/rows.length*100),end:100},{type:'slider',xAxisIndex:[0,1],height:16,bottom:1,start:Math.max(0,100-range/rows.length*100),end:100,borderColor:c.line}],series:[mode==='candle'?{name:'日K',type:'candlestick',data:rows.map(r=>[r[1],r[2],r[4],r[3]]),itemStyle:{color:c.red,color0:c.green,borderColor:c.red,borderColor0:c.green}}:{name:'收盘',type:'line',data:rows.map(r=>r[2]),showSymbol:false,lineStyle:{color:c.accent,width:2},areaStyle:{color:c.accent,opacity:.06}},...[[5,'#c99a37'],[20,'#8972b6']].map(([n,color])=>({name:'MA'+n,type:'line',showSymbol:false,data:M.movingAverage(rows,n),lineStyle:{width:1,color},itemStyle:{color}})),{name:'成交量',type:'bar',xAxisIndex:1,yAxisIndex:1,data:rows.map(r=>({value:r[5],itemStyle:{color:r[2]>=r[1]?c.red:c.green,opacity:.65}}))}]};chart(node,option,detail);
}
function indexRows(code){return(S.history.records?.[code]||[]).filter(r=>r[0]<=day());}
function indexInfo(code){const rows=indexRows(code),last=rows.at(-1),prior=rows.at(-2),meta=S.market.indices.find(x=>x.code===code);return last?{...meta,code,name:meta?.name||code,price:last[2],changePct:prior?(last[2]/prior[2]-1)*100:meta?.date===last[0]?meta.changePct:null,date:last[0]}:meta?.date===day()?meta:{code,name:meta?.name||code,price:null,changePct:null,date:null};}
function metric(label,value,note,cls=''){return `<div class="stat"><span>${label}</span><strong class="${cls}">${value}</strong><small>${note}</small></div>`;}
function render(){if(!S.data)return;dispose();S.view=routes[location.hash.slice(1)]?location.hash.slice(1):'overview';$('#page-title').textContent=routes[S.view][0];$('#page-kicker').textContent=routes[S.view][1];$$('nav a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+S.view);a.setAttribute('aria-current',a.hash==='#'+S.view?'page':'false');});$('#watch-count').textContent=S.watch.size||'';
 const age=(Date.now()-Date.parse(day()+'T15:00:00+08:00'))/864e5;$('#status').innerHTML=`<span class="status-live">● 收盘快照 <b>${esc(day())}</b></span><span>资金 ${S.data.stocks.length} 只 · 行情 ${Object.keys(S.quotes.records||{}).length} 只</span><span>成功采集 ${esc(S.data.meta.generatedAt)}</span><a href="#sources">数据状态 ↗</a>`;
 const failed=Object.entries(S.researchStatus?.sources||{}).filter(([,v])=>!v.ok).map(([k])=>k);const warnings=[age>4?'你正在查看历史快照，不是最新行情。':'',S.data.meta.lastError||'',failed.length?failed.join('、')+'最近更新失败，请在数据中心核对时间。':''];$('#alert').hidden=!warnings.some(Boolean);$('#alert').textContent=warnings.filter(Boolean).join(' ');
 ({overview:overview,rotation:rotation,stock:explorer,industry:explorer,concept:explorer,watch:explorer,events:eventsView,report:report,sources:sources})[S.view]();if(S.view==='sources')sourcesExtras();icons();renderCompareTray();}
function overview(){const stocks=S.data.stocks,up=stocks.filter(r=>r.changePct>0).length,down=stocks.filter(r=>r.changePct<0).length,flat=stocks.filter(r=>r.changePct===0).length,total=M.sum(stocks.map(r=>r.amount)),flow=M.sum(stocks.map(r=>r.netFlow)),indices=S.market.indices.map(r=>indexInfo(r.code)),leader=M.sortRows(S.data.industries,'netFlow')[0],strong=S.data.industries.filter(r=>r.netFlow>0).length;
 $('#content').innerHTML=`<div class="index-ribbon">${indices.map((r,i)=>`<button class="index-button ${r.code===S.index?'active':''}" data-index="${r.code}"><span class="index-name">${esc(r.name)}<span>${r.code===S.index?'●':''}</span></span><strong class="${tone(r.changePct)}">${num(r.price)}</strong><span class="index-change ${tone(r.changePct)}">${pct(r.changePct)}</span><div class="sparkline" id="spark-${i}"></div></button>`).join('')}</div><div class="overview-primary"><section class="work-section"><div class="section-head"><h2>${esc(indexInfo(S.index).name)} · 价格与成交量</h2><small>日线 · 腾讯公开行情</small></div><div class="chart-toolbar">${rangeButtons('index-range',S.range)}<span class="spacer"></span><div class="segmented"><button data-price-mode="candle" class="${S.priceMode==='candle'?'active':''}">日K</button><button data-price-mode="line" class="${S.priceMode==='line'?'active':''}">走势</button></div></div><div class="echart" id="index-chart"></div><div class="chart-foot"><span>MA5 / MA20 · 成交量为源站单位</span><span>历史自 2024-09-24</span></div></section><section class="work-section"><div class="section-head"><h2>市场广度</h2><small>资金覆盖样本</small></div><div class="breadth-stats"><div><strong class="up">${up}</strong><span>上涨</span></div><div><strong class="down">${down}</strong><span>下跌</span></div><div><strong>${flat}</strong><span>平盘</span></div></div><div class="breadth"><span style="flex:${up};background:var(--red)"></span><span style="flex:${flat};background:var(--muted)"></span><span style="flex:${down};background:var(--green)"></span></div><div class="compact-metrics"><div><label>样本成交额</label><strong>${money(total)}</strong></div><div><label>样本资金净额</label><strong class="${tone(flow)}">${money(flow)}</strong></div></div><div class="insight-row">${ico('chart-no-axes-combined')}<div><strong>${up>down?'上涨家数占优':'下跌家数占优'}</strong><small>上涨占比 ${num(up/stocks.length*100,1)}%，净流入行业 ${strong}/${S.data.industries.length}。</small></div></div><div class="insight-row">${ico('focus')}<div><strong>${esc(leader?.name||'--')} 净额排名靠前</strong><small>资金净额 ${money(leader?.netFlow)}，当日 ${pct(leader?.changePct)}。</small></div></div></section></div>
 <div class="market-bottom"><section class="work-section"><div class="section-head"><h2>行业全景</h2><div class="segmented"><button data-tree-metric="netFlow" class="${S.treeMetric==='netFlow'?'active':''}">资金</button><button data-tree-metric="changePct" class="${S.treeMetric==='changePct'?'active':''}">涨跌</button></div></div><div id="sector-tree" class="echart"></div><div class="chart-foot"><span>面积：成分数量 · 颜色：${S.treeMetric==='netFlow'?'资金净额':'涨跌幅'}</span><a href="#industry">行业明细 →</a></div></section><section class="work-section"><div class="section-head"><h2>涨跌幅分布</h2><small>不等同涨跌停统计</small></div><div id="distribution" class="echart small"></div><div class="section-head" style="margin-top:20px"><h2>市场快讯</h2><a href="#events">全部 →</a></div>${S.events.news.slice(0,3).map(e=>`<div class="event-row" style="padding:10px 0;grid-template-columns:45px 1fr;gap:10px"><time>${esc(e.time?.slice(11,16))}</time><h3><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a></h3></div>`).join('')}</section></div><section class="work-section"><div class="section-head"><h2>资金与价格的分歧</h2><small>同花顺行业 · 当日净额 × 涨跌幅</small></div><div id="flow-scatter" class="echart small"></div></section>`;
 indices.forEach((r,i)=>{const a=indexRows(r.code).slice(-25),c=colors();chart('#spark-'+i,{grid:{left:0,right:0,top:3,bottom:0},xAxis:{type:'category',show:false,data:a.map(x=>x[0])},yAxis:{type:'value',show:false,scale:true},series:[{type:'line',data:a.map(x=>x[2]),showSymbol:false,lineStyle:{width:1.3,color:r.changePct>=0?c.red:c.green},silent:true}]});});
 candles('#index-chart',indexRows(S.index),{range:S.range,mode:S.priceMode});$('.overview-primary .chart-foot span:last-child').textContent=`可用日线 ${indexRows(S.index).length} 条 · 起点 ${indexRows(S.index)[0]?.[0]||'--'}`;treemap('#sector-tree',S.data.industries,S.treeMetric);scatter('#flow-scatter',S.data.industries);
 const counts=[0,0,0,0,0,0,0,0,0];for(const r of stocks){const v=r.changePct;if(!M.valid(v))continue;const i=v<-7?0:v<-3?1:v<-1?2:v<0?3:v===0?4:v<=1?5:v<=3?6:v<=7?7:8;counts[i]++;}const c=colors();chart('#distribution',{grid:{left:35,right:10,top:25,bottom:30},xAxis:{type:'category',data:['<-7%','-7~-3','-3~-1','-1~0','平盘','0~1','1~3','3~7','>7%'],axisLabel:{fontSize:9},axisLine:{lineStyle:{color:c.line}}},yAxis:{show:false},tooltip:{trigger:'axis',confine:true},series:[{type:'bar',barWidth:'58%',label:{show:true,position:'top',fontSize:10,color:c.muted},data:counts.map((v,i)=>({value:v,itemStyle:{color:i<4?c.green:i===4?c.muted:c.red}}))}]});
}
function rangeButtons(attr,value){return `<div class="segmented">${[[60,'近3月'],[120,'近6月'],[250,'近1年'],[1000,'全部']].map(([n,t])=>`<button data-${attr}="${n}" class="${value===n?'active':''}">${t}</button>`).join('')}</div>`;}
function treemap(node,rows,metric){const c=colors(),max=Math.max(...rows.map(r=>Math.abs(r[metric]||0)),1);const instance=chart(node,{tooltip:{confine:true,formatter:p=>`${esc(p.name)}<br>净流入 ${money(p.data.raw.netFlow)}<br>涨跌幅 ${pct(p.data.raw.changePct)}<br>成分 ${p.data.raw.memberCount||'--'} 只`},series:[{type:'treemap',roam:false,nodeClick:false,breadcrumb:{show:false},top:1,bottom:1,left:1,right:1,leafDepth:1,visibleMin:20,label:{show:true,fontSize:12,color:c.ink,formatter:p=>`${p.name}\n${metric==='netFlow'?money(p.data.raw.netFlow):pct(p.data.raw.changePct)}`},itemStyle:{gapWidth:2,borderWidth:1,borderColor:c.surface},data:rows.map(r=>({name:r.name,value:Math.max(1,r.memberCount||1),raw:r,itemStyle:{color:r[metric]>=0?`rgba(200,60,73,${.12+Math.sqrt(Math.abs(r[metric]||0)/max)*.52})`:`rgba(24,131,101,${.12+Math.sqrt(Math.abs(r[metric]||0)/max)*.52})`}}))}]});instance?.on('click',p=>p.data?.raw&&openDetail(idOf(p.data.raw)));}
function scatter(node,rows){const c=colors();const instance=chart(node,{grid:{left:60,right:40,top:25,bottom:40},tooltip:{confine:true,formatter:p=>`${esc(p.data.name)}<br>净流入 ${money(p.data.value[0]*1e8)}<br>涨跌幅 ${pct(p.data.value[1])}`},xAxis:{type:'value',name:'净额 / 亿',nameLocation:'middle',nameGap:25,splitLine:{lineStyle:{color:c.line}}},yAxis:{type:'value',name:'涨跌幅 %',splitLine:{lineStyle:{color:c.line}}},series:[{type:'scatter',data:rows.filter(r=>M.valid(r.netFlow)&&M.valid(r.changePct)).map(r=>({name:r.name,raw:r,value:[r.netFlow/1e8,r.changePct,r.memberCount||10],symbolSize:Math.min(30,8+Math.sqrt(r.memberCount||10)),itemStyle:{color:r.netFlow>=0?c.red:c.green,opacity:.65}})),markLine:{silent:true,symbol:'none',label:{show:false},lineStyle:{color:c.muted,type:'dashed',opacity:.4},data:[{xAxis:0},{yAxis:0}]}}]});instance?.on('click',p=>p.data?.raw&&openDetail(idOf(p.data.raw)));}
function rotation(){const rows=(S.rotationType==='行业'?S.data.industries:S.data.concepts).map(enrich),top=M.sortRows(rows,'flow5')[0],improve=M.sortRows(rows,'delta')[0],persistent=rows.slice().sort((a,b)=>(b.stats.streak||0)-(a.stats.streak||0))[0];
 $('#content').innerHTML=`<div class="section-head"><h2>资金轮动地图</h2><div class="segmented"><button data-rotation-type="行业" class="${S.rotationType==='行业'?'active':''}">行业</button><button data-rotation-type="概念" class="${S.rotationType==='概念'?'active':''}">概念</button></div></div><p class="market-note">每日资金净额 · 空格代表数据缺失 · 排列为当前净流入前 20 名</p><div class="rotation-summary"><div><label>近5交易日净额居前</label><strong>${M.valid(top?.stats.flow5.value)?esc(top.name):'数据不完整'}</strong><small>${money(top?.stats.flow5.value)}</small></div><div><label>较上个交易日改善居前</label><strong>${M.valid(improve?.stats.delta)?esc(improve.name):'数据不完整'}</strong><small>净额变化 ${money(improve?.stats.delta)}</small></div><div><label>已确认连续流入</label><strong>${persistent?.stats.streak>0?esc(persistent.name):'暂无'}</strong><small>${persistent?.stats.streak>0?'至少 '+persistent.stats.streak+' 个交易日':'等待更多数据'}</small></div></div><div class="toolbar"><span class="hint">观察窗口</span><div class="segmented"><button data-rotation-days="10" class="${S.rotationDays===10?'active':''}">10 交易日</button><button data-rotation-days="20" class="${S.rotationDays===20?'active':''}">20 交易日</button></div></div><div id="rotation-chart" class="echart rotation-chart"></div><section class="work-section"><div class="section-head"><h2>当日与多日资金对照</h2><small>缺口不补值</small></div>${simpleRanking(rows.slice().sort((a,b)=>(b.stats.flow5.value??-Infinity)-(a.stats.flow5.value??-Infinity)).slice(0,15))}</section>`;
 const dates=S.analytics.calendar.filter(d=>d<=day()).slice(-S.rotationDays),leaders=M.sortRows(rows,'netFlow').slice(0,20).reverse(),values=[];
 leaders.forEach((r,y)=>{const map=new Map(seriesFor(r));dates.forEach((d,x)=>{if(M.valid(map.get(d)))values.push([x,y,map.get(d)/1e8]);});});const c=colors(),max=Math.max(...values.map(x=>Math.abs(x[2])),1);const instance=chart('#rotation-chart',{tooltip:{confine:true,formatter:p=>`${esc(leaders[p.value[1]].name)}<br>${dates[p.value[0]]}<br>净流入 ${money(p.value[2]*1e8)}`},grid:{left:100,right:20,top:20,bottom:64},xAxis:{type:'category',data:dates,axisLabel:{formatter:v=>v.slice(5),fontSize:10},splitArea:{show:true,areaStyle:{color:[c.surface,c.surface]}}},yAxis:{type:'category',data:leaders.map(r=>r.name),axisLabel:{fontSize:11},splitArea:{show:true,areaStyle:{color:[c.surface,c.surface]}}},visualMap:{min:-max,max,calculable:false,orient:'horizontal',left:'center',bottom:2,itemWidth:12,itemHeight:140,text:['流入','流出'],textStyle:{color:c.muted},inRange:{color:[c.green,c.surface,c.red]}},series:[{type:'heatmap',data:values,label:{show:S.rotationDays===10,formatter:p=>num(p.value[2],1),fontSize:10,color:c.ink},itemStyle:{borderColor:c.surface,borderWidth:3},emphasis:{itemStyle:{borderColor:c.accent,borderWidth:2}}}]});instance?.on('click',async p=>{const r=leaders[p.value[1]],d=dates[p.value[0]];if(S.archive.some(a=>a.date===d)){S.date=d;await load();openDetail(idOf(r));}});
}
function simpleRanking(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>当日净流入</th><th>近5日净额</th><th>近20日净额</th><th>净额变化</th><th>连续流入</th></tr></thead><tbody>${rows.map(r=>`<tr><td style="text-align:left"><button class="name" data-detail="${esc(idOf(r))}">${esc(r.name)}</button></td><td class="${tone(r.netFlow)}">${money(r.netFlow)}</td><td class="${tone(r.stats.flow5.value)}" title="覆盖 ${r.stats.flow5.covered}/5 个交易日">${money(r.stats.flow5.value)}</td><td class="${tone(r.stats.flow20.value)}" title="覆盖 ${r.stats.flow20.covered}/20 个交易日">${money(r.stats.flow20.value)}</td><td class="${tone(r.stats.delta)}">${money(r.stats.delta)}</td><td>${r.stats.streak?'≥'+r.stats.streak+'日':'--'}</td></tr>`).join('')}</tbody></table></div>`;}
function explorer(){const isStock=S.view==='stock'||S.view==='watch';let intro='';if(S.view==='watch'){
 const rows=baseRows().map(enrich),stocks=rows.filter(r=>r.code),alerts=stocks.filter(r=>{const note=S.notes[idOf(r)];return note&&((M.valid(note.above)&&r.price>=note.above)||(M.valid(note.below)&&r.price<=note.below));});
 intro=`<div class="watch-overview"><div><span>当前快照内自选</span><strong>${rows.length}</strong><small>已保存 ${S.watch.size} 项</small></div><div><span>上涨 / 下跌</span><strong>${rows.filter(r=>r.changePct>0).length} / ${rows.filter(r=>r.changePct<0).length}</strong><small>行业、概念、个股</small></div><div><span>自选个股资金净额</span><strong class="${tone(M.sum(stocks.map(r=>r.netFlow)))}">${money(M.sum(stocks.map(r=>r.netFlow)))}</strong><small>不合计交叉板块</small></div><div><span>已达观察价位</span><strong>${alerts.length}</strong><small>按当前快照价格判断</small></div></div>${alerts.map(r=>`<div class="watch-alert">${ico('bell')}<span>${esc(r.name)} ${num(r.price)} · 已达到你设定的观察价位</span><button data-detail="${esc(idOf(r))}">查看</button></div>`).join('')}`;
 if(!S.watch.size){$('#content').innerHTML=`<div class="watch-empty">${ico('star')}<h2>建立你的市场观察清单</h2><p>自选、笔记与观察价位保存在当前浏览器。</p><a href="#stock">个股探索 →</a><a href="#industry">行业资金 →</a></div>`;return;}}
 $('#content').innerHTML=intro+`<p class="market-note">${isStock?'同花顺资金 · 腾讯行情与估值 · 估值仅在行情日期与资金日期一致时显示':'同花顺分类 · 净流入率 = 净额 /（流入额 + 流出额）'} · 多日指标缺失时显示 --</p><div class="toolbar"><input id="table-search" type="search" placeholder="搜索名称或代码" aria-label="筛选名称或代码" value="${esc(S.query)}"><div class="segmented">${[['all','全部'],['in','净流入'],['out','净流出'],['diverge','量价分歧']].map(([k,t])=>`<button data-direction="${k}" class="${S.direction===k?'active':''}">${t}</button>`).join('')}</div><span class="spacer"></span>${!isStock?`<div class="segmented"><button data-chart-mode="table" class="${S.chartMode==='table'?'active':''}">表格</button><button data-chart-mode="heat" class="${S.chartMode==='heat'?'active':''}">全景</button></div>`:''}${iconButton('download','导出筛选结果','data-export="csv"')}${S.view==='watch'?iconButton('archive','备份自选与笔记','data-export="watch"')+iconButton('upload','恢复自选备份','data-import="watch"')+'<input id="watch-file" type="file" accept="application/json" hidden>':''}</div><div class="toolbar"><div class="segmented">${[['all','全部状态'],['strength','流入且上涨'],['persistent','连续流入≥3日'],['improving','净额改善']].map(([k,t])=>`<button data-preset="${k}" class="${S.preset===k?'active':''}">${t}</button>`).join('')}</div></div>${isStock?`<details class="filters-panel"><summary>${ico('sliders-horizontal')} 估值与交易条件</summary><div class="filter-fields"><label>市场<select id="filter-exchange"><option value="all">全部市场</option><option value="sh">沪市</option><option value="sz">深市</option><option value="bj">北交所</option></select></label>${[['peMax','市盈率上限'],['capMin','总市值下限 / 亿'],['turnMin','换手率下限 / %'],['flowMin','净流入下限 / 亿']].map(([k,t])=>`<label>${t}<input type="number" step="any" id="filter-${k}" value="${esc(S[k])}" placeholder="不限"></label>`).join('')}<label class="checklabel"><input id="filter-noST" type="checkbox" ${S.noST?'checked':''}>排除 ST</label><button data-reset-filters>清空条件</button></div></details>`:''}<div id="board-map"></div><div id="table-summary" class="screen-summary"></div><div id="table-area"></div>`;
 $('#table-search').oninput=e=>{S.query=e.target.value;S.page=1;renderTable();};if(isStock){$('#filter-exchange').value=S.exchange;$('#filter-exchange').onchange=e=>{S.exchange=e.target.value;S.page=1;renderTable();};$('#filter-noST').onchange=e=>{S.noST=e.target.checked;S.page=1;renderTable();};for(const k of ['peMax','capMin','turnMin','flowMin'])$('#filter-'+k).oninput=e=>{S[k]=e.target.value;S.page=1;renderTable();};}if($('#watch-file'))$('#watch-file').onchange=importWatch;renderTable();
}
function renderTable(){const oldChart=$('#explorer-tree');if(oldChart&&window.echarts){const old=echarts.getInstanceByDom(oldChart);if(old){old.dispose();S.charts=S.charts.filter(c=>c!==old);}}const rows=tableRows(),pages=Math.max(1,Math.ceil(rows.length/40));S.page=Math.min(S.page,pages);const stock=S.view==='stock'||S.view==='watch';const cols=stock?[['price','现价'],['changePct','涨跌幅'],['netFlow','当日净流入'],['flow5','近5日净额'],['amount','成交额'],['turnover','换手率'],['pe','市盈率'],['pb','市净率'],['marketCap','总市值']]:[['netFlow','当日净流入'],['flow5','近5日净额'],['flow20','近20日净额'],['delta','净额变化'],['changePct','涨跌幅'],['flowRate','净流入率']];
 $('#table-summary').innerHTML=`<span>匹配 <b>${rows.length}</b> ${stock?'项':'个板块'}</span><span>净流入 <b class="up">${rows.filter(r=>r.netFlow>0).length}</b></span><span>净流出 <b class="down">${rows.filter(r=>r.netFlow<0).length}</b></span>`;
 if(!stock&&S.chartMode==='heat'){$('#board-map').innerHTML='<div class="echart board-chart" id="explorer-tree"></div>';treemap('#explorer-tree',rows,'netFlow');}else $('#board-map').innerHTML='';
 const cell=(r,k)=>k==='flow5'||k==='flow20'?money(r.stats[k].value):k==='delta'?money(r.stats.delta):['netFlow','amount','marketCap'].includes(k)?money(r[k]):['changePct','flowRate','turnover'].includes(k)?pct(r[k]):num(r[k]);
 const value=(r,k)=>k==='flow5'||k==='flow20'?r.stats[k].value:k==='delta'?r.stats.delta:r[k];
 $('#table-area').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>自选 / 对比</th><th>名称</th>${cols.map(([k,t])=>`<th aria-sort="${S.sort===k?(S.sortDirection===-1?'descending':'ascending'):'none'}"><button data-sort="${k}">${t} ${S.sort===k?(S.sortDirection===-1?'↓':'↑'):''}</button></th>`).join('')}</tr></thead><tbody>${rows.slice((S.page-1)*40,S.page*40).map(r=>`<tr><td><button class="mini-action ${S.watch.has(idOf(r))?'selected':''}" data-star="${esc(idOf(r))}" title="${S.watch.has(idOf(r))?'取消自选':'加入自选'}" aria-label="自选 ${esc(r.name)}">${ico('star')}</button><button class="mini-action ${S.compare.includes(idOf(r))?'compare-selected':''}" data-compare="${esc(idOf(r))}" title="加入对比" aria-label="对比 ${esc(r.name)}">${ico('git-compare')}</button></td><td class="name-cell"><button class="name" data-detail="${esc(idOf(r))}">${esc(r.name)}</button><small class="subcode">${esc(r.code||r.category)} ${S.notes[idOf(r)]?.text?'<span class="note-badge">· 有笔记</span>':''}</small></td>${cols.map(([k])=>`<td class="number-cell ${['netFlow','flow5','flow20','delta','changePct','flowRate'].includes(k)?tone(value(r,k)):''}" ${['flow5','flow20'].includes(k)?`title="覆盖 ${r.stats[k].covered}/${r.stats[k].total} 个交易日"`:''}>${cell(r,k)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length+2}">${empty('没有符合条件的记录')}</td></tr>`}</tbody></table></div><div class="pagination"><span>共 ${rows.length} 项 · 每页40项</span><div><button data-page="${S.page-1}" ${S.page<=1?'disabled':''} title="上一页" aria-label="上一页">${ico('chevron-left')}</button><span>${S.page} / ${pages}</span><button data-page="${S.page+1}" ${S.page>=pages?'disabled':''} title="下一页" aria-label="下一页">${ico('chevron-right')}</button></div></div>`;icons();}
function resetFilters(){Object.assign(S,{query:'',direction:'all',exchange:'all',preset:'all',noST:false,peMax:'',capMin:'',turnMin:'',flowMin:'',page:1});}
async function stockFlows(){if(!S.stockFlows)S.stockFlows=await getJSON('data/stock-flows.json');return S.stockFlows;}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const q=v=>'"'+String(v??'').replaceAll('"','""').replace(/^[=+@]/,'\t$&')+'"';const rows=tableRows();const lines=[['名称','代码','类型','日期','净流入(元)','涨跌幅(%)','近5日净额(元)','市盈率','市净率','总市值(元)'],...rows.map(r=>[r.name,r.code?'\t'+r.code:'',r.category,day(),r.netFlow,r.changePct,r.stats.flow5.value,r.pe,r.pb,r.marketCap])];download('A股研究-'+day()+'.csv','\ufeff'+lines.map(row=>row.map(q).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
async function importWatch(e){try{const text=await e.target.files[0].text();if(text.length>500000)throw new Error('备份过大');const d=JSON.parse(text);if(!Array.isArray(d.watch)||d.watch.some(x=>typeof x!=='string'||x.length>100))throw new Error('无效的自选备份');const notes={};for(const [k,v] of Object.entries(d.notes||{})){if(!v||typeof v!=='object')continue;notes[k]={text:String(v.text||'').slice(0,10000),above:M.valid(v.above)?Number(v.above):null,below:M.valid(v.below)?Number(v.below):null};}S.watch=new Set([...S.watch,...d.watch]);S.notes={...S.notes,...notes};persist('a-watch',[...S.watch]);persist('a-notes',S.notes);render();toast('已合并自选和笔记');}catch(err){toast('无法导入：'+err.message);}}
async function kline(r){const code=exchange(r.code)+r.code,cache=code+':'+day();if(S.kline.has(cache))return S.kline.get(cache);const d=await getJSON(`https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=${code},day,2024-09-24,${day()},640,qfq`),rows=d.data?.[code]?.qfqday||d.data?.[code]?.day;if(!rows?.length)throw new Error('源站没有返回该股票的历史日线');const result=rows.filter(x=>x[0]<=day()).map(x=>[x[0],...x.slice(1,6).map(Number)]);S.kline.set(cache,result);return result;}
function openDetail(id){const base=allBase().find(r=>idOf(r)===id);if(!base)return;S.detail=id;S.detailTab=base.code?'price':'flow';S.detailRange=120;$('#detail-title').textContent=base.name+(base.code?' · '+base.code:'');if(!$('#detail').open)$('#detail').showModal();renderDetail();$('#search-results').hidden=true;}
async function renderDetail(){const ticket=++S.detailRequest,base=allBase().find(r=>idOf(r)===S.detail);if(!base)return;dispose(true);const r=enrich(base),isStock=!!r.code;
 const metrics=isStock?[['当日净额',money(r.netFlow)],['近5日净额',money(r.stats.flow5.value)],['市盈率',num(r.pe)],['市净率',num(r.pb)],['换手率',pct(r.turnover)],['总市值',money(r.marketCap)]]:[['当日净额',money(r.netFlow)],['近5日净额',money(r.stats.flow5.value)],['近20日净额',money(r.stats.flow20.value)],['净流入率',pct(r.flowRate)],['成分数量',num(r.memberCount,0)],['连续流入',r.stats.streak?'≥'+r.stats.streak+'日':'--']];
 $('#detail-body').innerHTML=`<div class="security-meta"><strong class="security-price ${tone(r.changePct)}">${num(r.price??r.indexValue)}</strong><span class="${tone(r.changePct)}">${pct(r.changePct)}</span><span>${esc(day())} · ${esc(r.category)}</span><span class="spacer"></span><button class="${S.watch.has(S.detail)?'selected':''}" data-star="${esc(S.detail)}">${ico('star')} ${S.watch.has(S.detail)?'已自选':'加入自选'}</button><button data-compare="${esc(S.detail)}">${ico('git-compare')} 对比</button></div><div class="security-metrics">${metrics.map(([t,v])=>`<div><span>${t}</span><strong>${v}</strong></div>`).join('')}</div><div class="detail-tabs">${[...(isStock?[['price','价格与成交量']]:[]),['flow','资金轨迹'],...(isStock?[['announcements','相关公告']]:[]),['notes','我的研究笔记']].map(([k,t])=>`<button data-detail-tab="${k}" class="${S.detailTab===k?'active':''}">${t}</button>`).join('')}</div><div id="detail-panel"></div>`;icons();const panel=$('#detail-panel');
 if(isStock){$('[data-detail-tab="announcements"]').insertAdjacentHTML('beforebegin',`<button data-detail-tab="financial" class="${S.detailTab==='financial'?'active':''}">财报摘要</button>`);}
 if(S.detailTab==='price'){panel.innerHTML=`<div class="chart-toolbar">${rangeButtons('detail-range',S.detailRange)}<span class="hint">前复权日线 · 腾讯公开行情</span></div><div id="security-chart" class="echart tall">${loading()}</div><div class="chart-foot"><span>开 ${num(r.open)} · 高 ${num(r.high)} · 低 ${num(r.low)} · 昨收 ${num(r.previous)}</span><span>日线按需读取；失败不替代数据</span></div>`;try{const rows=await kline(r);if(ticket!==S.detailRequest)return;$('#security-chart').innerHTML='';candles('#security-chart',rows,{detail:true,range:S.detailRange});}catch(e){if(ticket===S.detailRequest)$('#security-chart').innerHTML=empty('日线暂不可用：'+e.message);}}
 else if(S.detailTab==='flow'){panel.innerHTML=loading();try{if(isStock)await stockFlows();if(ticket!==S.detailRequest)return;const series=seriesFor(r),map=new Map(series),dates=S.analytics.calendar.filter(d=>d<=day()).slice(-30),stats=M.stockStats(S.analytics.calendar,series,day());panel.innerHTML=`<p class="hint">近5交易日覆盖 ${stats.flow5.covered}/5 · 近20交易日覆盖 ${stats.flow20.covered}/20 · 空缺日期不连线、不累计</p><div id="security-flow" class="echart"></div><div class="table-wrap flow-table"><table><thead><tr><th>交易日</th><th>资金净额</th><th>数据状态</th></tr></thead><tbody>${dates.slice().reverse().slice(0,15).map(d=>`<tr><td>${d}</td><td class="${tone(map.get(d))}">${money(map.get(d))}</td><td>${M.valid(map.get(d))?'已采集':'缺失'}</td></tr>`).join('')}</tbody></table></div>`;lineChart('#security-flow',dates,[{name:r.name,data:dates.map(d=>M.valid(map.get(d))?map.get(d)/1e8:null)}],true);}catch(e){if(ticket===S.detailRequest)panel.innerHTML=empty('资金历史读取失败：'+e.message);}}
 else if(S.detailTab==='financial'){await financialPanel(r,panel,ticket);}
 else if(S.detailTab==='announcements'){const rows=S.events.announcements.filter(e=>e.codes.includes(r.code));panel.innerHTML=`<p class="hint">最新公告索引 · 采集 ${esc(S.events.announcementsAt||'--')} · 与回看日期独立</p>${rows.length?rows.map(eventRow).join(''):empty('当前采集范围内暂无匹配公告，不代表该公司没有公告')}<div class="detail-links"><a href="https://data.eastmoney.com/notices/stock/${r.code}.html" target="_blank" rel="noopener noreferrer">完整公告列表 ↗</a><a href="https://www.cninfo.com.cn/" target="_blank" rel="noopener noreferrer">巨潮资讯核对原文 ↗</a></div>`;}
 else {const note=S.notes[S.detail]||{};panel.innerHTML=`<div class="note-editor"><label>研究笔记<textarea id="note-text" placeholder="记录关注原因、需要核实的问题和后续观察…">${esc(note.text||'')}</textarea></label>${isStock?`<div class="thresholds"><label>观察价位上沿 / 元<input type="number" min="0" step="0.01" id="note-above" value="${esc(note.above??'')}" placeholder="未设置"></label><label>观察价位下沿 / 元<input type="number" min="0" step="0.01" id="note-below" value="${esc(note.below??'')}" placeholder="未设置"></label></div>`:''}<p class="hint">仅保存在当前浏览器。价位提示基于收盘快照，不是实时预警，也不会向外发送通知。</p><button id="save-note">保存笔记</button></div>`;$('#save-note').onclick=()=>{const above=$('#note-above')?.value,below=$('#note-below')?.value;if(M.valid(above)&&M.valid(below)&&Number(above)<=Number(below)){toast('上沿需要高于下沿');return;}S.notes[S.detail]={text:$('#note-text').value.slice(0,10000),above:M.valid(above)?Number(above):null,below:M.valid(below)?Number(below):null};S.watch.add(S.detail);persist('a-notes',S.notes);persist('a-watch',[...S.watch]);toast('笔记已保存');$('#watch-count').textContent=S.watch.size;};}icons();}
async function financialPanel(r,panel,ticket){
 panel.innerHTML=loading();
 try{
  S.financials??=await getJSON('data/financials.json');S.financialChunks??={};
  const prefix=r.code.slice(0,3);
  if(!S.financials.shards.includes(prefix)){panel.innerHTML=empty('没有取得该公司的财报摘要');return;}
  S.financialChunks[prefix]??=await getJSON('data/financials/'+prefix+'.json');
  if(ticket!==S.detailRequest)return;
  const rows=(S.financialChunks[prefix].records[r.code]||[]).slice(0,8),latest=rows[0];
  if(!latest){panel.innerHTML=empty('没有取得该公司的财报摘要');return;}
  panel.innerHTML=`<p class="hint">东方财富财务摘要 · 采集 ${esc(S.financials.generatedAt)} · 最新整理版本，与资金回看日期独立</p><h3>${esc(latest.type)} <small class="hint">公告 ${esc(latest.noticeDate)}</small></h3><div class="security-metrics" style="grid-template-columns:repeat(4,1fr)">${[['营业收入',money(latest.revenue)],['归母净利润',money(latest.profit)],['加权ROE',pct(latest.roe)],['每股经营现金流',num(latest.cashPerShare)+'元']].map(([t,v])=>`<div><span>${t}</span><strong>${v}</strong></div>`).join('')}</div><div id="financial-chart" class="echart small"></div><p class="hint">营收与利润为报告期本年累计值，不是单季度值；同比与ROE采用源站定义。</p><div class="table-wrap"><table class="data-table"><thead><tr><th>报告期</th><th>营业收入</th><th>营收同比</th><th>归母净利润</th><th>净利同比</th><th>加权ROE</th><th>每股收益</th><th>每股经营现金流</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.period}</td><td>${money(x.revenue)}</td><td class="${tone(x.revenueGrowth)}">${pct(x.revenueGrowth)}</td><td>${money(x.profit)}</td><td class="${tone(x.profitGrowth)}">${pct(x.profitGrowth)}</td><td>${pct(x.roe)}</td><td>${num(x.eps)}</td><td>${num(x.cashPerShare)}</td></tr>`).join('')}</tbody></table></div><div class="detail-links"><a target="_blank" rel="noopener noreferrer" href="https://data.eastmoney.com/bbsj/${r.code}.html">完整财务信息 ↗</a><a target="_blank" rel="noopener noreferrer" href="https://www.cninfo.com.cn/">公告原文核对 ↗</a></div>`;
  const c=colors(),chronological=rows.slice().reverse();chart('#financial-chart',{tooltip:{trigger:'axis',confine:true,valueFormatter:v=>num(v)+'亿'},legend:{data:['营业收入','归母净利润'],textStyle:{color:c.muted}},grid:{left:55,right:20,top:32,bottom:28},xAxis:{type:'category',data:chronological.map(x=>x.period),axisLabel:{fontSize:10},axisLine:{lineStyle:{color:c.line}}},yAxis:{type:'value',name:'亿元',splitLine:{lineStyle:{color:c.line}}},series:[{name:'营业收入',type:'bar',itemStyle:{color:c.accent},data:chronological.map(x=>M.valid(x.revenue)?x.revenue/1e8:null)},{name:'归母净利润',type:'bar',itemStyle:{color:'#ba9343'},data:chronological.map(x=>M.valid(x.profit)?x.profit/1e8:null)}]},true);
 }catch(e){if(ticket===S.detailRequest)panel.innerHTML=empty('财报摘要读取失败：'+e.message);}
}
function renderCompareTray(){const tray=$('#compare-tray');tray.hidden=!S.compare.length;tray.innerHTML=S.compare.map(id=>{const r=allBase().find(r=>idOf(r)===id);return `<span class="compare-chip">${esc(r?.name||id)}<button data-compare="${esc(id)}" aria-label="移除对比">${ico('x')}</button></span>`;}).join('')+`<button data-open-compare ${S.compare.length<2?'disabled':''}>对比 ${S.compare.length}/4</button><button data-clear-compare>清空</button>`;icons();}
async function compareView(){if(S.compare.length<2)return;S.detail=null;const ticket=++S.detailRequest;dispose(true);$('#detail-title').textContent='资金对比';$('#detail-body').innerHTML=loading();if(!$('#detail').open)$('#detail').showModal();try{const rows=S.compare.map(id=>allBase().find(r=>idOf(r)===id)).filter(Boolean).map(enrich);if(rows.some(r=>r.code))await stockFlows();if(ticket!==S.detailRequest)return;const dates=S.analytics.calendar.filter(d=>d<=day()).slice(-30);$('#detail-body').innerHTML=`<div class="compare-header">${rows.map(r=>`<div><strong>${esc(r.name)}</strong><p>${esc(r.category)} · ${pct(r.changePct)}</p><span class="${tone(r.netFlow)}">${money(r.netFlow)}</span></div>`).join('')}</div><p class="hint">每日净额 / 亿元 · 不同规模标的的绝对金额不可直接代表强弱 · 缺失日保留空白</p><div id="compare-chart" class="echart tall"></div>${simpleRanking(rows)}`;lineChart('#compare-chart',dates,rows.map(r=>{const map=new Map(seriesFor(r));return {name:r.name,data:dates.map(d=>M.valid(map.get(d))?map.get(d)/1e8:null)};}),true);}catch(e){$('#detail-body').innerHTML=empty('对比数据读取失败：'+e.message);}}
function topic(e){const t=e.title;return /证监|央行|国务院|财政|监管|政策|发改|降息|降准/.test(t)?'政策':/芯片|半导体|算力|人工智能|机器人|光伏|新能源|创新药|产业|大模型|汽车/.test(t)?'产业':/美联储|美国|欧洲|俄罗斯|伊朗|德国|日经|纳指|道指|美元|黄金|原油/.test(t)?'海外':e.codes?.length?'公司':'综合';}
function eventRow(e){return `<article class="event-row"><time>${esc(e.time?.slice(5,10)||'--')}<br>${esc(e.time?.slice(11,16)||'--')}</time><div><h3><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a></h3><div class="event-meta"><span>${e.category?esc(e.category):topic(e)}</span><span>东方财富${e.category?'公告索引':'快讯'}</span>${(e.codes||[]).slice(0,3).map(code=>{const r=S.data.stocks.find(r=>r.code===code);return r?`<button data-detail="个股:${code}">${esc(r.name)} ↗</button>`:'';}).join('')}</div></div></article>`;}
function eventList(){let rows=[...(S.eventType!=='announcements'?S.events.news:[]),...(S.eventType!=='news'?S.events.announcements:[])];return rows.filter(e=>(S.eventCategory==='all'||topic(e)===S.eventCategory)&&(S.eventQuery===''||`${e.title} ${(e.codes||[]).join(' ')} ${(e.names||[]).join(' ')}`.includes(S.eventQuery))).sort((a,b)=>(b.time||'').localeCompare(a.time||''));}
function eventsView(){const rows=eventList(),pages=Math.max(1,Math.ceil(rows.length/25));S.eventPage=Math.min(S.eventPage,pages);$('#content').innerHTML=`<div class="toolbar"><div class="segmented">${[['all','全部'],['news','市场快讯'],['announcements','公司公告']].map(([k,t])=>`<button data-event-type="${k}" class="${S.eventType===k?'active':''}">${t}</button>`).join('')}</div><input id="event-search" type="search" placeholder="搜索标题、公司或代码" aria-label="搜索快讯与公告" value="${esc(S.eventQuery)}"><span class="spacer"></span><span class="hint">最新信息 · 与回看日期独立</span></div><div class="events-layout"><div>${rows.slice((S.eventPage-1)*25,S.eventPage*25).map(eventRow).join('')||empty('没有匹配的快讯或公告')}<div class="pagination"><span>${rows.length} 条</span><div><button data-event-page="${S.eventPage-1}" ${S.eventPage===1?'disabled':''}>←</button><span>${S.eventPage}/${pages}</span><button data-event-page="${S.eventPage+1}" ${S.eventPage===pages?'disabled':''}>→</button></div></div></div><aside class="event-aside"><h3>主题</h3><div class="category-list">${[['all','全部主题'],['政策','政策'],['产业','产业'],['公司','公司'],['海外','海外'],['综合','综合']].map(([k,t])=>`<button data-event-category="${k}" class="${S.eventCategory===k?'active':''}">${t}</button>`).join('')}</div><section class="work-section"><h3>信息来源</h3><p>快讯 ${S.events.news.length} 条<br>采集 ${esc(S.events.newsAt||'--')}</p><p>公告 ${S.events.announcements.length} 条<br>采集 ${esc(S.events.announcementsAt||'--')}</p><p>本站只保留标题、时间与原文链接。主题按标题关键词分组；涉及公司事项以公告原文为准。</p>${(S.events.errors||[]).map(e=>`<p>${esc(e)}</p>`).join('')}</section></aside></div>`;let timer;$('#event-search').oninput=e=>{S.eventQuery=e.target.value;S.eventPage=1;clearTimeout(timer);timer=setTimeout(()=>{eventsView();$('#event-search').focus();},350);};}
function report(){const stocks=S.data.stocks.map(enrich),industries=S.data.industries.map(enrich),up=stocks.filter(r=>r.changePct>0).length,down=stocks.filter(r=>r.changePct<0).length,flow=M.sum(stocks.map(r=>r.netFlow)),amount=M.sum(stocks.map(r=>r.amount)),leaders=M.sortRows(industries.filter(r=>r.netFlow>0),'netFlow').slice(0,3),laggards=M.sortRows(industries.filter(r=>r.netFlow<0),'netFlow',1).slice(0,3),persistent=M.sortRows(industries,'flow5').filter(r=>M.valid(r.stats.flow5.value)).slice(0,5),diverge=M.sortRows(stocks.filter(r=>r.netFlow>0&&r.changePct<0),'netFlow').slice(0,5);const names=rows=>rows.map(r=>`${esc(r.name)}（${money(r.netFlow)}）`).join('、')||'暂无';const pe=M.median(stocks.map(r=>r.pe>0?r.pe:null)),pb=M.median(stocks.map(r=>r.pb>0?r.pb:null)),positivePe=stocks.filter(r=>r.pe>0).length;
 $('#content').innerHTML=`<article class="report"><div class="report-controls">${iconButton('printer','打印或另存PDF','data-print-report')}</div><p class="report-date">${esc(day())} / 每日市场研究</p><h2>市场广度、资金方向与观察清单</h2><p class="report-subtitle">基于已覆盖样本的规则化复盘 · 同花顺资金 / 腾讯行情 · 不包含收益预测</p><div class="report-kpis"><div><span>样本成交额</span><strong>${money(amount)}</strong></div><div><span>样本净流入</span><strong class="${tone(flow)}">${money(flow)}</strong></div><div><span>上涨 / 下跌</span><strong>${up} / ${down}</strong></div><div><span>净流入行业</span><strong>${industries.filter(r=>r.netFlow>0).length} / ${industries.length}</strong></div></div><h3>01 · 市场表现</h3><p>${S.market.indices.map(r=>indexInfo(r.code)).map(r=>`${esc(r.name)} ${pct(r.changePct)}`).join('；')}。</p><p>覆盖 ${stocks.length} 只个股，上涨 ${up} 只、下跌 ${down} 只，上涨占比 ${num(up/stocks.length*100,1)}%。${up>down?'上涨家数占优，样本广度偏强。':'下跌家数占优，样本广度偏弱。'}这一判断只衡量覆盖个股的方向分布，不代表每只股票的表现。</p><h3>02 · 资金方向</h3><p>行业净流入居前：${names(leaders)}。净流出居前：${names(laggards)}。</p><p>近5个交易日净额居前的方向见下表。未覆盖完整交易日的板块不参与多日排名。</p>${persistent.length?simpleRanking(persistent):empty('近5交易日数据不完整，暂不列出多日排名')}<h3>03 · 估值截面</h3><p>${positivePe?`同日有效正市盈率样本 ${positivePe} 只，中位数 ${num(pe)} 倍；正市净率样本中位数 ${num(pb)} 倍。亏损、缺失和非正值未纳入上述中位数。行业差异较大，不能把这一截面视为整体市场的买卖信号。`:'当前快照没有同日估值数据，不生成估值判断。'}</p><h3>04 · 需要继续核实的分歧</h3><p>当日下跌但净流入为正、且净额靠前的个股：${names(diverge)}。成交方向与价格方向不一致，可能受到成交结构影响；单日分歧不代表后续反转。</p><blockquote>后续观察：检查主要流入行业是否在更多交易日保持正净额；将个股价格、成交量和正式公告放在一起核实。历史缺口会降低连续性判断的可靠性。</blockquote><h3>05 · 信息与覆盖</h3><p>已存资金日期 ${S.archive.length} 个，目标起点 2024-09-24，实际可用起点 ${esc(S.archive[0]?.date||'--')}。源站资金页没有逐条日期，日期采用收盘后的指数交易日校验。快讯和公告按最新采集时间展示，不自动归因于当天涨跌。</p><p class="report-subtitle">资料来源：同花顺公开资金流、腾讯公开行情、东方财富快讯与公告索引。个股净流入率与行业净流入率分母不同；概念存在重叠，不合计。</p></article>`;}
function sources(){const rows=[['同花顺资金快照',`${S.data.industries.length} 行业 / ${S.data.concepts.length} 概念 / ${S.data.stocks.length} 个股`,S.data.meta.generatedAt,'当日资金及价格方向；行业分类为同花顺口径。','https://data.10jqka.com.cn/funds/'],['腾讯个股行情',`${Object.keys(S.quotes.records).length} 只 · 缺失 ${S.quotes.missing?.length||0} 只`,S.quotes.generatedAt,'价格、换手、行情口径市盈率、市净率、总市值。估值仅在日期一致时显示。','https://stockapp.finance.qq.com/'],['腾讯历史日线','指数与个股日K',S.history.generatedAt,'指数不复权；个股前复权，按需从公开接口读取。不能与不复权成交价混用。','https://gu.qq.com/'],['市场快讯',`${S.events.news.length} 条标题`,S.events.newsAt,'仅保存标题、时间、关联代码和原文链接；并非完整资讯数据库。','https://kuaixun.eastmoney.com/7_24.html'],['公司公告',`${S.events.announcements.length} 条公告索引`,S.events.announcementsAt,'最近采集范围内的公司公告，不代表全量历史。以法定披露原文为准。','https://www.cninfo.com.cn/'],['历史资金分析',`${S.archive.length} 个已存日期`,S.analytics.generatedAt,'按指数日线交易日校验5日、20日窗口；缺失不补值。','https://data.10jqka.com.cn/']];const available=new Set(S.archive.map(x=>x.date)),dates=S.analytics.calendar.filter(d=>d<=day()).slice(-60);
 $('#content').innerHTML=`<div class="resource-grid">${rows.map(([title,count,time,note,url])=>`<article class="resource"><span class="source-health">${esc(count)}</span><h3>${title}</h3><small>${esc(time||'未取得')}</small><p>${note}</p><a href="${url}" target="_blank" rel="noopener noreferrer">来源 ↗</a></article>`).join('')}</div><section class="work-section"><div class="section-head"><h2>资金历史覆盖日历</h2><small>最近60个已确认交易日 · 实心已存 / 虚线缺失</small></div><div class="coverage-grid">${dates.map(d=>available.has(d)?`<button class="coverage-day" data-date="${d}">${d.slice(5)}</button>`:`<span class="coverage-day missing" style="display:grid;place-items:center" title="${d} 数据缺失">${d.slice(5)}</span>`).join('')}</div><p class="hint">目标历史自 2024-09-24。更早资金记录没有取得，未以其他供应商替代。原站历史恢复数据保留旧采集器记录的日期。</p></section><section class="work-section"><h2>尚未完整接入的内容</h2><p class="market-note" style="margin-top:15px">财务报表逐季明细、龙虎榜、融资融券余额、基金持仓与宏观时间序列尚未结构化接入；以下为原始信息入口。</p><div class="resource-grid">${[['交易与龙虎榜','https://www.sse.com.cn/','上海证券交易所'],['财报与公司披露','https://www.cninfo.com.cn/','巨潮资讯'],['深市与交易公开信息','https://www.szse.cn/','深圳证券交易所'],['北交所市场','https://www.bse.cn/','北京证券交易所'],['货币与金融统计','https://www.pbc.gov.cn/','中国人民银行'],['宏观与经济统计','https://www.stats.gov.cn/','国家统计局']].map(([t,u,s])=>`<article class="resource"><h3>${t}</h3><a href="${u}" target="_blank" rel="noopener noreferrer">${s} ↗</a></article>`).join('')}</div></section><p class="hint">每个工作日16:35尝试更新，平台排队可能延迟。失败保留最近成功数据与原日期。自选、笔记和观察价位只保存在当前浏览器。</p>`;}
function sourcesExtras(){
 $('#content > .resource-grid').insertAdjacentHTML('beforeend',`<article class="resource"><span class="source-health">财报核心摘要 · 按需读取</span><h3>东方财富财务数据</h3><small>覆盖报告期自 2024-09-24</small><p>营收、归母净利润、同比、ROE、每股收益与每股经营现金流。按源站最新整理版本展示，不作历史时点版本回溯。</p><a href="https://data.eastmoney.com/bbsj/" target="_blank" rel="noopener noreferrer">来源 ↗</a></article>`);
 $('#content .work-section:nth-of-type(2) .market-note').textContent='财报核心摘要已经接入；完整三大财务报表科目、龙虎榜、融资融券余额、基金持仓与宏观时间序列尚未完整结构化接入，以下为原始信息入口。';
 const failures=Object.entries(S.researchStatus?.sources||{}).filter(([,x])=>!x.ok);if(failures.length)$('#content').insertAdjacentHTML('afterbegin',`<p class="source-error">最近更新异常：${failures.map(([k,v])=>esc(k+'：'+v.error)).join('；')}</p>`);
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.detail){openDetail(d.detail);return;}
 if(d.star){S.watch.has(d.star)?S.watch.delete(d.star):S.watch.add(d.star);persist('a-watch',[...S.watch]);$('#watch-count').textContent=S.watch.size;const detailOpen=$('#detail').open;if(['stock','industry','concept','watch'].includes(S.view))render();if(detailOpen&&S.detail)renderDetail();return;}
 if(d.compare){const at=S.compare.indexOf(d.compare);if(at>=0)S.compare.splice(at,1);else if(S.compare.length<4)S.compare.push(d.compare);else toast('最多同时对比4个标的');renderCompareTray();if($('#table-area'))renderTable();return;}
 if(Object.hasOwn(d,'clearCompare')){S.compare=[];renderCompareTray();if($('#table-area'))renderTable();return;}
 if(Object.hasOwn(d,'openCompare')){compareView();return;}
 if(d.index){S.index=d.index;render();return;}if(d.indexRange){S.range=Number(d.indexRange);render();return;}if(d.priceMode){S.priceMode=d.priceMode;render();return;}
 if(d.treeMetric){S.treeMetric=d.treeMetric;render();return;}if(d.rotationType){S.rotationType=d.rotationType;render();return;}if(d.rotationDays){S.rotationDays=Number(d.rotationDays);render();return;}
 if(d.direction){S.direction=d.direction;S.page=1;render();return;}if(d.preset){S.preset=d.preset;S.page=1;render();return;}if(d.chartMode){S.chartMode=d.chartMode;render();return;}
 if(d.sort){S.sortDirection=S.sort===d.sort?-S.sortDirection:-1;S.sort=d.sort;renderTable();return;}if(d.page){S.page=Number(d.page);renderTable();return;}
 if(Object.hasOwn(d,'resetFilters')){resetFilters();render();return;}
 if(d.export==='csv'){exportCSV();return;}if(d.export==='watch'){download('A股自选备份.json',JSON.stringify({version:1,watch:[...S.watch],notes:S.notes},null,2),'application/json');return;}if(d.import==='watch'){$('#watch-file').click();return;}
 if(d.detailTab){S.detailTab=d.detailTab;renderDetail();return;}if(d.detailRange){S.detailRange=Number(d.detailRange);renderDetail();return;}
 if(d.eventType){S.eventType=d.eventType;S.eventPage=1;render();return;}if(d.eventCategory){S.eventCategory=d.eventCategory;S.eventPage=1;render();return;}if(d.eventPage){S.eventPage=Number(d.eventPage);render();return;}
 if(d.date){S.date=d.date;await load();return;}if(Object.hasOwn(d,'printReport'))window.print();
});
$('#global-search').oninput=e=>{const q=e.target.value.trim().toLowerCase(),box=$('#search-results');box.hidden=!q;if(!q)return;const rows=allBase().filter(r=>`${r.name} ${r.code||''}`.toLowerCase().includes(q)).sort((a,b)=>(b.code===q?1:0)-(a.code===q?1:0)).slice(0,9);box.innerHTML=rows.map(r=>`<button data-detail="${esc(idOf(r))}"><span>${esc(r.name)}</span><small>${esc(r.code||r.category)}</small></button>`).join('')||empty('没有匹配结果');};
$('#global-search').onkeydown=e=>{if(e.key==='Enter')$('#search-results button')?.click();if(e.key==='Escape')$('#search-results').hidden=true;};
document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))$('#search-results').hidden=true;});
$('#date-select').onchange=async e=>{S.date=e.target.value;S.page=1;if($('#detail').open)$('#detail').close();if(S.date!=='latest'&&['stock','watch'].includes(S.view)){try{await stockFlows();}catch{}}load();};
$('#refresh').onclick=()=>{S.stockFlows=null;S.financials=null;S.financialChunks={};S.kline.clear();load();};$('#theme').onclick=()=>{document.body.classList.toggle('dark');persist('a-theme',document.body.classList.contains('dark')?'dark':'light');render();if($('#detail').open){S.detail?renderDetail():compareView();}};
$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{S.detailRequest++;dispose(true);});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});
window.addEventListener('hashchange',async()=>{resetFilters();if(S.date!=='latest'&&['#stock','#watch'].includes(location.hash)){try{await stockFlows();}catch{}}render();window.scrollTo({top:0});});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>[...S.charts,...S.detailCharts].forEach(c=>!c.isDisposed()&&c.resize()),120);});
icons();load();
